name: Create blocklist

on:
  schedule:
    - cron:  '0 0 * * *'    # every night at midnight UTC
  workflow_dispatch:        # manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 1
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create blocklists
        run: python3 scripts/blocklist-update.py

      # - name: Verify output files exist
      #   run: |
      #     mkdir -p releases
      #     if [ ! -f releases/blocklist.txt ]; then
      #       echo "Error: One or more output files are missing!"
      #       exit 1
      #     fi
      # - name: Run git pull
      #   run: git pull origin main
        
      # - name: Commit outputs
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     git add blocklist.txt
      #     # only commit if there are changes
      #     git diff --quiet && echo "No changes to commit" || git commit -m "chore: update blocklist lists"
      #     git push origin main
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if git commit -m "Generate blocklists"; then
            git push
          fi
